package bean;
// Generated 16/10/2023 17:57:48 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OibDistribuidora generated by hbm2java
 */
@Entity
@Table(name="oib_distribuidora"
    ,catalog="db_oscar_britez"
)
public class OibDistribuidora  implements java.io.Serializable {


     private int idDistribuidora;
     private String oibNome;
     private String oibCarro;
     private String oibQuantidade;
     private Date oibDataEnvio;
     private Date oibTempoEntrega;
     private String oibPreco;

    public OibDistribuidora() {
    }

    public OibDistribuidora(int idDistribuidora, String oibNome, String oibCarro, String oibQuantidade, Date oibDataEnvio, Date oibTempoEntrega, String oibPreco) {
       this.idDistribuidora = idDistribuidora;
       this.oibNome = oibNome;
       this.oibCarro = oibCarro;
       this.oibQuantidade = oibQuantidade;
       this.oibDataEnvio = oibDataEnvio;
       this.oibTempoEntrega = oibTempoEntrega;
       this.oibPreco = oibPreco;
    }
   
     @Id 

    
    @Column(name="idDistribuidora", unique=true, nullable=false)
    public int getIdDistribuidora() {
        return this.idDistribuidora;
    }
    
    public void setIdDistribuidora(int idDistribuidora) {
        this.idDistribuidora = idDistribuidora;
    }

    
    @Column(name="oib_nome", nullable=false, length=45)
    public String getOibNome() {
        return this.oibNome;
    }
    
    public void setOibNome(String oibNome) {
        this.oibNome = oibNome;
    }

    
    @Column(name="oib_carro", nullable=false, length=45)
    public String getOibCarro() {
        return this.oibCarro;
    }
    
    public void setOibCarro(String oibCarro) {
        this.oibCarro = oibCarro;
    }

    
    @Column(name="oib_quantidade", nullable=false, length=45)
    public String getOibQuantidade() {
        return this.oibQuantidade;
    }
    
    public void setOibQuantidade(String oibQuantidade) {
        this.oibQuantidade = oibQuantidade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="oib_dataEnvio", nullable=false, length=10)
    public Date getOibDataEnvio() {
        return this.oibDataEnvio;
    }
    
    public void setOibDataEnvio(Date oibDataEnvio) {
        this.oibDataEnvio = oibDataEnvio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="oib_tempoEntrega", nullable=false, length=10)
    public Date getOibTempoEntrega() {
        return this.oibTempoEntrega;
    }
    
    public void setOibTempoEntrega(Date oibTempoEntrega) {
        this.oibTempoEntrega = oibTempoEntrega;
    }

    
    @Column(name="oib_preco", nullable=false, length=45)
    public String getOibPreco() {
        return this.oibPreco;
    }
    
    public void setOibPreco(String oibPreco) {
        this.oibPreco = oibPreco;
    }




}


