package bean;
// Generated 16/10/2023 17:57:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OibFuncionario generated by hbm2java
 */
@Entity
@Table(name="oib_funcionario"
    ,catalog="db_oscar_britez"
)
public class OibFuncionario  implements java.io.Serializable {
    public static void insert(OibFuncionario oibfuncionario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



     private int idFuncionario;
     private String oibNome;
     private String oibSobrenome;
     private String oibCpf;
     private Date oibDataNascimento;
     private Integer oibTelefone;
     private int oibLogin;
     private int oibFuncao;
     private Set oibVendas = new HashSet(0);

    public OibFuncionario() {
    }

	
    public OibFuncionario(int idFuncionario, String oibNome, String oibSobrenome, String oibCpf, Date oibDataNascimento, int oibLogin, int oibFuncao) {
        this.idFuncionario = idFuncionario;
        this.oibNome = oibNome;
        this.oibSobrenome = oibSobrenome;
        this.oibCpf = oibCpf;
        this.oibDataNascimento = oibDataNascimento;
        this.oibLogin = oibLogin;
        this.oibFuncao = oibFuncao;
    }
    public OibFuncionario(int idFuncionario, String oibNome, String oibSobrenome, String oibCpf, Date oibDataNascimento, Integer oibTelefone, int oibLogin, int oibFuncao, Set oibVendas) {
       this.idFuncionario = idFuncionario;
       this.oibNome = oibNome;
       this.oibSobrenome = oibSobrenome;
       this.oibCpf = oibCpf;
       this.oibDataNascimento = oibDataNascimento;
       this.oibTelefone = oibTelefone;
       this.oibLogin = oibLogin;
       this.oibFuncao = oibFuncao;
       this.oibVendas = oibVendas;
    }
   
     @Id 

    
    @Column(name="idFuncionario", unique=true, nullable=false)
    public int getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(int idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

    
    @Column(name="oib_nome", nullable=false, length=45)
    public String getOibNome() {
        return this.oibNome;
    }
    
    public void setOibNome(String oibNome) {
        this.oibNome = oibNome;
    }

    
    @Column(name="oib_sobrenome", nullable=false, length=45)
    public String getOibSobrenome() {
        return this.oibSobrenome;
    }
    
    public void setOibSobrenome(String oibSobrenome) {
        this.oibSobrenome = oibSobrenome;
    }

    
    @Column(name="oib_cpf", nullable=false, length=14)
    public String getOibCpf() {
        return this.oibCpf;
    }
    
    public void setOibCpf(String oibCpf) {
        this.oibCpf = oibCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="oib_dataNascimento", nullable=false, length=10)
    public Date getOibDataNascimento() {
        return this.oibDataNascimento;
    }
    
    public void setOibDataNascimento(Date oibDataNascimento) {
        this.oibDataNascimento = oibDataNascimento;
    }

    
    @Column(name="oib_telefone")
    public Integer getOibTelefone() {
        return this.oibTelefone;
    }
    
    public void setOibTelefone(Integer oibTelefone) {
        this.oibTelefone = oibTelefone;
    }

    
    @Column(name="oib_login", nullable=false)
    public int getOibLogin() {
        return this.oibLogin;
    }
    
    public void setOibLogin(int oibLogin) {
        this.oibLogin = oibLogin;
    }

    
    @Column(name="oib_funcao", nullable=false)
    public int getOibFuncao() {
        return this.oibFuncao;
    }
    
    public void setOibFuncao(int oibFuncao) {
        this.oibFuncao = oibFuncao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oibFuncionario")
    public Set getOibVendas() {
        return this.oibVendas;
    }
    
    public void setOibVendas(Set oibVendas) {
        this.oibVendas = oibVendas;
    }




}


