package bean;
// Generated 16/10/2023 17:57:48 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OibProduto generated by hbm2java
 */
@Entity
@Table(name="oib_produto"
    ,catalog="db_oscar_britez"
)
public class OibProduto  implements java.io.Serializable {


     private int idProduto;
     private String marca;
     private String modelo;
     private String preco;
     private String cor;
     private Date chegada;

    public OibProduto() {
    }

	
    public OibProduto(int idProduto, String marca, String modelo, String preco, String cor) {
        this.idProduto = idProduto;
        this.marca = marca;
        this.modelo = modelo;
        this.preco = preco;
        this.cor = cor;
    }
    public OibProduto(int idProduto, String marca, String modelo, String preco, String cor, Date chegada) {
       this.idProduto = idProduto;
       this.marca = marca;
       this.modelo = modelo;
       this.preco = preco;
       this.cor = cor;
       this.chegada = chegada;
    }
   
     @Id 

    
    @Column(name="idProduto", unique=true, nullable=false)
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }

    
    @Column(name="marca", nullable=false, length=45)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="modelo", nullable=false, length=45)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="preco", nullable=false, length=45)
    public String getPreco() {
        return this.preco;
    }
    
    public void setPreco(String preco) {
        this.preco = preco;
    }

    
    @Column(name="cor", nullable=false, length=20)
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="chegada", length=10)
    public Date getChegada() {
        return this.chegada;
    }
    
    public void setChegada(Date chegada) {
        this.chegada = chegada;
    }




}


