package bean;
// Generated 16/10/2023 17:57:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OibUsuarios generated by hbm2java
 */
@Entity
@Table(name="oib_usuarios"
    ,catalog="db_oscar_britez"
)
public class OibUsuarios  implements java.io.Serializable {


     private int idUsuarios;
     private String oibNome;
     private String oibApelido;
     private String oibCpf;
     private String oibDataNascimento;
     private int oibSenha;
     private int oibNivel;
     private String oibAtivo;

    public OibUsuarios() {
    }

    public OibUsuarios(int idUsuarios, String oibNome, String oibApelido, String oibCpf, String oibDataNascimento, int oibSenha, int oibNivel, String oibAtivo) {
       this.idUsuarios = idUsuarios;
       this.oibNome = oibNome;
       this.oibApelido = oibApelido;
       this.oibCpf = oibCpf;
       this.oibDataNascimento = oibDataNascimento;
       this.oibSenha = oibSenha;
       this.oibNivel = oibNivel;
       this.oibAtivo = oibAtivo;
    }
   
     @Id 

    
    @Column(name="idUsuarios", unique=true, nullable=false)
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }

    
    @Column(name="oib_nome", nullable=false, length=45)
    public String getOibNome() {
        return this.oibNome;
    }
    
    public void setOibNome(String oibNome) {
        this.oibNome = oibNome;
    }

    
    @Column(name="oib_apelido", nullable=false, length=45)
    public String getOibApelido() {
        return this.oibApelido;
    }
    
    public void setOibApelido(String oibApelido) {
        this.oibApelido = oibApelido;
    }

    
    @Column(name="oib_cpf", nullable=false, length=14)
    public String getOibCpf() {
        return this.oibCpf;
    }
    
    public void setOibCpf(String oibCpf) {
        this.oibCpf = oibCpf;
    }

    
    @Column(name="oib_dataNascimento", nullable=false, length=45)
    public String getOibDataNascimento() {
        return this.oibDataNascimento;
    }
    
    public void setOibDataNascimento(String oibDataNascimento) {
        this.oibDataNascimento = oibDataNascimento;
    }

    
    @Column(name="oib_senha", nullable=false)
    public int getOibSenha() {
        return this.oibSenha;
    }
    
    public void setOibSenha(int oibSenha) {
        this.oibSenha = oibSenha;
    }

    
    @Column(name="oib_nivel", nullable=false)
    public int getOibNivel() {
        return this.oibNivel;
    }
    
    public void setOibNivel(int oibNivel) {
        this.oibNivel = oibNivel;
    }

    
    @Column(name="oib_ativo", nullable=false, length=45)
    public String getOibAtivo() {
        return this.oibAtivo;
    }
    
    public void setOibAtivo(String oibAtivo) {
        this.oibAtivo = oibAtivo;
    }




}


