package bean;
// Generated 16/10/2023 17:57:48 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OibVenda generated by hbm2java
 */
@Entity
@Table(name="oib_venda"
    ,catalog="db_oscar_britez"
)
public class OibVenda  implements java.io.Serializable {


     private int idVenda;
     private OibClientes oibClientes;
     private OibFuncionario oibFuncionario;
     private Date oibData;
     private int oibTotal;
     private String oibFormaPagamento;
     private OibVendaproduto oibVendaproduto;

    public OibVenda() {
    }

	
    public OibVenda(int idVenda, OibClientes oibClientes, OibFuncionario oibFuncionario, Date oibData, int oibTotal, String oibFormaPagamento) {
        this.idVenda = idVenda;
        this.oibClientes = oibClientes;
        this.oibFuncionario = oibFuncionario;
        this.oibData = oibData;
        this.oibTotal = oibTotal;
        this.oibFormaPagamento = oibFormaPagamento;
    }
    public OibVenda(int idVenda, OibClientes oibClientes, OibFuncionario oibFuncionario, Date oibData, int oibTotal, String oibFormaPagamento, OibVendaproduto oibVendaproduto) {
       this.idVenda = idVenda;
       this.oibClientes = oibClientes;
       this.oibFuncionario = oibFuncionario;
       this.oibData = oibData;
       this.oibTotal = oibTotal;
       this.oibFormaPagamento = oibFormaPagamento;
       this.oibVendaproduto = oibVendaproduto;
    }
   
     @Id 

    
    @Column(name="idVenda", unique=true, nullable=false)
    public int getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(int idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oib_fkClientes", nullable=false)
    public OibClientes getOibClientes() {
        return this.oibClientes;
    }
    
    public void setOibClientes(OibClientes oibClientes) {
        this.oibClientes = oibClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oib_fkVendedor", nullable=false)
    public OibFuncionario getOibFuncionario() {
        return this.oibFuncionario;
    }
    
    public void setOibFuncionario(OibFuncionario oibFuncionario) {
        this.oibFuncionario = oibFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="oib_data", nullable=false, length=10)
    public Date getOibData() {
        return this.oibData;
    }
    
    public void setOibData(Date oibData) {
        this.oibData = oibData;
    }

    
    @Column(name="oib_total", nullable=false)
    public int getOibTotal() {
        return this.oibTotal;
    }
    
    public void setOibTotal(int oibTotal) {
        this.oibTotal = oibTotal;
    }

    
    @Column(name="oib_formaPagamento", nullable=false, length=45)
    public String getOibFormaPagamento() {
        return this.oibFormaPagamento;
    }
    
    public void setOibFormaPagamento(String oibFormaPagamento) {
        this.oibFormaPagamento = oibFormaPagamento;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="oibVenda")
    public OibVendaproduto getOibVendaproduto() {
        return this.oibVendaproduto;
    }
    
    public void setOibVendaproduto(OibVendaproduto oibVendaproduto) {
        this.oibVendaproduto = oibVendaproduto;
    }




}


