package bean;
// Generated 16/10/2023 17:57:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OibVendaproduto generated by hbm2java
 */
@Entity
@Table(name="oib_vendaproduto"
    ,catalog="db_oscar_britez"
)
public class OibVendaproduto  implements java.io.Serializable {


     private int idVendaProduto;
     private OibVenda oibVenda;

    public OibVendaproduto() {
    }

    public OibVendaproduto(OibVenda oibVenda) {
       this.oibVenda = oibVenda;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="oibVenda"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idVendaProduto", unique=true, nullable=false)
    public int getIdVendaProduto() {
        return this.idVendaProduto;
    }
    
    public void setIdVendaProduto(int idVendaProduto) {
        this.idVendaProduto = idVendaProduto;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public OibVenda getOibVenda() {
        return this.oibVenda;
    }
    
    public void setOibVenda(OibVenda oibVenda) {
        this.oibVenda = oibVenda;
    }




}


